---
title: "Lesson spatial data"
Author: "Me:
---


## Setup


```{r}

out_dir <- here::here('data/ak_regions')

if(!dir.exists(out_dir)) { # this is helpful because then it ONLY downloads once. If R sees that
    knb_url <- "https://dev.nceas.ucsb.edu/knb/d1/mn/v2/object/urn%3Auuid%3Aaceaecb2-1ce0-4d41-a839-d3607d32bb58"

    download.file(url = knb_url, 
                  destfile = 'shapefile_demo_data.zip', 
                  mode = 'wb')

    unzip('shapefile_demo_data.zip', exdir = out_dir)

    file.remove('shapefile_demo_data.zip')
}

```

```{r packages}
### Data wrangling packages:
library(readr)
library(dplyr)
library(tidyr)
library(here)

### Simple Features vector spatial data:
library(sf)

### Data visualization packages:
library(ggplot2)
library(leaflet)
library(scales)
library(ggspatial)
```

## Data Exploration


```{r}
ak_rgns_sf <- read_sf(here("data/ak_regions/ak_regions_simp.shp"))

# explore datum and projection
st_crs(ak_rgns_sf)

# 4326 projection is BAD in alaska, so transform to a better projection
#note: a lot of state agenices talk about specific CRS that they recommend
# UTMs: more general use cases than calling out a specific CRS
ak_rgns_3338_sf <- ak_rgns_sf %>%
    st_transform(crs = 3338)

plot(ak_rgns_3338_sf)
glimpse(ak_rgns_3338_sf)
summary(ak_rgns_3338_sf)

# st_crs(ak_rgns_3338_sf) ### run in console to check
```

## Spatial Joins


```{r}
# population data
out_file <- here::here('data/alaska_population.csv')

if(!file.exists(out_file)) {
    pop_data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A7fc6f6db-c5ea-426a-a743-1f2edafb43b8"

    download.file(url = pop_data_url, 
                  destfile = out_file, 
                  mode = 'w')
}

# just a regular csv!
pop_df <- read_csv(here("data/alaska_population.csv")) %>%
    filter(Year == 2015) %>%
    select(city, lat, lng, population = total) %>%
    drop_na()

# turn it into a spatial object
pop_4326_sf <- st_as_sf(pop_df,
                        coords = c('lng', 'lat'), #This refers to the associated column names in the dataframe; x is longitude, y is latitude
                        crs = 4326, # lng and lat originally defined as 4326
                        remove = FALSE) # keep lng and lat columns for later


# make it so both are in the same CRS
pop_3338_sf <- st_transform(pop_4326_sf, 
                            crs = 3338)

pop_joined_sf <- st_join(pop_3338_sf, 
                         ak_rgns_3338_sf, 
                         join = st_within) # look at population within different regions

head(pop_joined_sf)

# save it

write_sf(pop_joined_sf, here("data/ak_regions_population.gpkg")) # writes the whole geopackage instead of just the shp

```

# Analysis

```{r}
# total population?
pop_rgn_df <- pop_joined_sf %>%
    st_drop_geometry() %>%
    group_by(region) %>%
    summarize(total_pop = sum(population))

# add pop data to regions data
pop_rgn_3338_sf <- left_join(ak_rgns_3338_sf, 
                             pop_rgn_df, 
                             by = "region")

### plot to check
plot(pop_rgn_3338_sf["total_pop"])

# Dissolving a geometry
# what if we want to look by management area?
pop_mgmt_3338_sf <- pop_rgn_3338_sf %>%
    group_by(mgmt_area) %>%
    summarize(total_pop = sum(total_pop))

plot(pop_mgmt_3338_sf["total_pop"])
```

# Visualizations


```{r}
#initial plot 
ggplot(pop_rgn_3338_sf) +
    geom_sf(aes(fill = total_pop)) +
    #labs(fill = "Total Population") +
    scale_fill_continuous(low = "khaki", high =  "firebrick",
                          labels = comma, name = "Population") + # "comma" is from one of the packages # name: this is what it will get called on the map, but does the same thing as "labs"
    theme_bw()

rivers_3338_sf <- read_sf(here("data/ak_regions/ak_rivers_simp.shp"))

ggplot() +
    geom_sf(data = pop_rgn_3338_sf, 
            mapping = aes(fill = total_pop)) +
    geom_sf(data = rivers_3338_sf,
            aes(linewidth = StrOrder),
            color = 'blue', alpha = .5) +
    scale_linewidth(range = c(0.05, 0.5),
                    guide = "none") +
    geom_sf(data = pop_3338_sf, size = 0.5, color = 'grey20') +
    labs(title = "Total Population by Alaska Region",
         fill = "Total Population") +
    scale_fill_continuous(low = "khaki",
                          high =  "firebrick",
                          labels = comma) +
    theme_bw() 


# incorporate base maps
library(prettymapr) # need this for the basemap tile
pop_3857_sf <- st_transform(pop_3338_sf, 
                         crs = 3857)

ggplot(data = pop_3857_sf) +
    ggspatial::annotation_map_tile(type = "osm", zoom = 6, progress = 'none') + 
    # higher zoom values are more detailed 
    geom_sf(aes(color = population),
            fill = NA) +
    coord_sf(xlim = c(-16900000, -16300000), ylim = c(8400000, 9000000)) +
    scale_color_continuous(low = "darkkhaki",
                           high =  "firebrick",
                           labels = comma)

                         
```
